### ISSUE TITLE
AssertionError when running tests

### ISSUE THREAD

**Issue by patrikhuber** [ybayle/Scyland3D#11]
Hi,

When I clone the git repo and run the tests, I'm getting the following error:

```
(scyland3d-review) patrik:/mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D$ ../test.sh
Testing call from python...
Using default example directory: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/example/
File successfully generated: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/landmarks.csv
Using default example directory: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/example/
File successfully generated: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/landmarks_reordered.csv
Using default example directory: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/example/
File successfully generated: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/landmarks_reversed.csv
Testing default behavior...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/Scyland3D.py", line 486, in test_no_regression
    _validation_against_ref()
  File "/mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/Scyland3D.py", line 391, in _validation_against_ref
    dirn + "landmarks.csv", dirn + "test/landmarks_ref.csv"
  File "/mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/Scyland3D.py", line 383, in _same_file
    assert line_ref == line_test, "Invalid line " + line_ref
AssertionError: Invalid line example/200118G_canicula_mediterranean_40_female_mature_lower_tooth04_4.pts,23.760645,14.822544,26.607994,23.460169,14.72399,26.149445,23.619444,14.667845,26.251095,23.519606,14.463796,25.761469,23.799814,14.451308,26.218939,23.817883,14.327648,26.021515,24.05011,14.500256,26.583118,23.731268,14.851231,26.612024,23.693602,14.879261,26.590559,23.657339,14.899388,26.562233,23.620415,14.917179,26.531328,23.591503,14.916238,26.493502,23.580864,14.887245,26.456419,23.555262,14.877494,26.415607,23.52702,14.865196,26.368336,23.579859,14.780132,26.356867,23.546961,14.772367,26.300602,23.504704,14.757745,26.230452,23.531639,14.690864,26.178947,23.574799,14.58428,26.049805,23.669212,14.445662,26.010353,23.800825,14.386982,26.109592,23.858444,14.317473,26.077599,23.894411,14.332585,26.170313,23.92621,14.366543,26.286236,23.955145,14.364937,26.324955,23.982096,14.327062,26.290644,24.00683,14.300524,26.272785,24.027893,14.302449,26.299009,24.04743,14.317135,26.343693,24.0672,14.343269,26.407444,24.082382,14.387399,26.492682,24.071802,14.447412,26.555712,23.957222,14.536147,26.573864,23.874788,14.572289,26.542034,23.817228,14.613439,26.521942,23.779778,14.664021,26.510342,23.76063,14.742847,26.568264,200118G,canicula,mediterranean,40,female,mature,lower,tooth04,4

Testing call from the command line...
Using default example directory: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/example/
File successfully generated: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/landmarks.csv
Using default example directory: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/example/
Traceback (most recent call last):
  File "Scyland3D.py", line 490, in <module>
    main(sys.argv[1:])
  File "Scyland3D.py", line 374, in main
    verbose=verbose,
  File "Scyland3D.py", line 211, in pts2csv
    ), "Must supply order and order_factor."
AssertionError: Must supply order and order_factor.
Using default example directory: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/example/
File successfully generated: /mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/landmarks_reversed.csv
Testing default behavior...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/Scyland3D.py", line 391, in _validation_against_ref
    dirn + "landmarks.csv", dirn + "test/landmarks_ref.csv"
  File "/mnt/c/Users/Patrik/Projects/Scyland3D-review/Scyland3D/Scyland3D/Scyland3D.py", line 383, in _same_file
    assert line_ref == line_test, "Invalid line " + line_ref
AssertionError: Invalid line example/200118G_canicula_mediterranean_40_female_mature_lower_tooth04_4.pts,23.760645,14.822544,26.607994,23.460169,14.72399,26.149445,23.619444,14.667845,26.251095,23.519606,14.463796,25.761469,23.799814,14.451308,26.218939,23.817883,14.327648,26.021515,24.05011,14.500256,26.583118,23.731268,14.851231,26.612024,23.693602,14.879261,26.590559,23.657339,14.899388,26.562233,23.620415,14.917179,26.531328,23.591503,14.916238,26.493502,23.580864,14.887245,26.456419,23.555262,14.877494,26.415607,23.52702,14.865196,26.368336,23.579859,14.780132,26.356867,23.546961,14.772367,26.300602,23.504704,14.757745,26.230452,23.531639,14.690864,26.178947,23.574799,14.58428,26.049805,23.669212,14.445662,26.010353,23.800825,14.386982,26.109592,23.858444,14.317473,26.077599,23.894411,14.332585,26.170313,23.92621,14.366543,26.286236,23.955145,14.364937,26.324955,23.982096,14.327062,26.290644,24.00683,14.300524,26.272785,24.027893,14.302449,26.299009,24.04743,14.317135,26.343693,24.0672,14.343269,26.407444,24.082382,14.387399,26.492682,24.071802,14.447412,26.555712,23.957222,14.536147,26.573864,23.874788,14.572289,26.542034,23.817228,14.613439,26.521942,23.779778,14.664021,26.510342,23.76063,14.742847,26.568264,200118G,canicula,mediterranean,40,female,mature,lower,tooth04,4
```

The `Invalid line ` error could in theory be a newline inconsistency since I'm using WSL - just a guess. The `AssertionError: Must supply order and order_factor.` error looks like something else.

Any idea what I might be doing wrong?

**Comment by Kevin-Mattheus-Moerman** [comment]
@ybayle :wave: any updates on handling this issue?

**Comment by ybayle** [comment]
Thanks for raising this issue. I fixed `The AssertionError: Must supply order and order_factor.`. For the WSL related issue, I have added verbosity in the test to help figure out the problem. If you don't reproduce it with the last version, please let me know.

**Comment by patrikhuber** [comment]
The `Must supply order and order_factor.` error seems gone.

There's a different error now:

```
(scyland3d) C:\Users\Patrik>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from Scyland3D import Scyland3D
>>> Scyland3D.test_no_regression()
File successfully generated: C:\Users\Patrik\Envs\scyland3d\lib\site-packages\Scyland3D\landmarks.csv
File successfully generated: C:\Users\Patrik\Envs\scyland3d\lib\site-packages\Scyland3D\landmarks_reordered.csv
File successfully generated: C:\Users\Patrik\Envs\scyland3d\lib\site-packages\Scyland3D\landmarks_reversed.csv
Testing default behavior...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Patrik\Envs\scyland3d\lib\site-packages\Scyland3D\Scyland3D.py", line 459, in test_no_regression
    _validation_against_ref()
  File "C:\Users\Patrik\Envs\scyland3d\lib\site-packages\Scyland3D\Scyland3D.py", line 351, in _validation_against_ref
    dirn + "landmarks.csv", dirn + "test/landmarks_ref.csv"
  File "C:\Users\Patrik\Envs\scyland3d\lib\site-packages\Scyland3D\Scyland3D.py", line 334, in _same_file
    assert line_ref == line_test, "Invalid line generated:\n" + line_test + "\nthat is different from the reference file:\n" + line_ref
AssertionError: Invalid line generated:
example/200118G_canicula_mediterranean_40_female_mature_lower_tooth09_4.pts,25.628664,11.627904,23.958033,25.294479,11.766243,23.443439,25.416937,11.636269,23.504972,25.285938,11.601955,23.1847,25.480515,11.458488,23.40572,25.424305,11.401969,23.213655,25.720415,11.227379,23.608505,25.605238,11.68239,23.968342,25.581594,11.735225,23.951746,25.55871,11.775233,23.927303,25.535694,11.803462,23.898464,25.509012,11.828192,23.866955,25.481352,11.8446,23.82785,25.486269,11.775678,23.780958,25.443384,11.805834,23.732676,25.394228,11.839259,23.66806,25.410519,11.719546,23.634127,25.351175,11.754179,23.546564,25.337692,11.711373,23.459862,25.341736,11.625697,23.339272,25.361479,11.536088,23.272907,25.453016,11.429392,23.314713,25.506357,11.353887,23.309586,25.548668,11.321219,23.384398,25.550634,11.305209,23.380384,25.552917,11.292115,23.362726,25.55512,11.280545,23.327475,25.565844,11.266936,23.305206,25.586967,11.251483,23.31579,25.614349,11.235746,23.352438,25.64748,11.214075,23.401062,25.69471,11.177201,23.487968,25.711798,11.199377,23.571569,25.649658,11.312396,23.602541,25.589733,11.408429,23.600561,25.570297,11.46718,23.659069,25.563253,11.537304,23.721621,25.585634,11.584576,23.828579,200118G,canicula,mediterranean,40,female,mature,lower,tooth09,4

that is different from the reference file:


>>>
```

This is on regular Windows (haven't tested WSL again so far). I still suspect it may have to do with line endings.

**Comment by patrikhuber** [comment]
Got an error in WSL as well:

```
(scyland3d) patrik:~/scyland3d-review/Scyland3D/Scyland3D$ ../test.sh
Testing call from python...
File successfully generated: /home/patrik/scyland3d-review/Scyland3D/Scyland3D/landmarks.csv
File successfully generated: /home/patrik/scyland3d-review/Scyland3D/Scyland3D/landmarks_reordered.csv
File successfully generated: /home/patrik/scyland3d-review/Scyland3D/Scyland3D/landmarks_reversed.csv
Testing default behavior...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/patrik/scyland3d-review/Scyland3D/Scyland3D/Scyland3D.py", line 459, in test_no_regression
    _validation_against_ref()
  File "/home/patrik/scyland3d-review/Scyland3D/Scyland3D/Scyland3D.py", line 351, in _validation_against_ref
    dirn + "landmarks.csv", dirn + "test/landmarks_ref.csv"
  File "/home/patrik/scyland3d-review/Scyland3D/Scyland3D/Scyland3D.py", line 334, in _same_file
    assert line_ref == line_test, "Invalid line generated:\n" + line_test + "\nthat is different from the reference file:\n" + line_ref
AssertionError: Invalid line generated:
example/200118G_canicula_mediterranean_40_female_mature_lower_tooth09_4.pts,25.628664,11.627904,23.958033,25.294479,11.766243,23.443439,25.416937,11.636269,23.504972,25.285938,11.601955,23.1847,25.480515,11.458488,23.40572,25.424305,11.401969,23.213655,25.720415,11.227379,23.608505,25.605238,11.68239,23.968342,25.581594,11.735225,23.951746,25.55871,11.775233,23.927303,25.535694,11.803462,23.898464,25.509012,11.828192,23.866955,25.481352,11.8446,23.82785,25.486269,11.775678,23.780958,25.443384,11.805834,23.732676,25.394228,11.839259,23.66806,25.410519,11.719546,23.634127,25.351175,11.754179,23.546564,25.337692,11.711373,23.459862,25.341736,11.625697,23.339272,25.361479,11.536088,23.272907,25.453016,11.429392,23.314713,25.506357,11.353887,23.309586,25.548668,11.321219,23.384398,25.550634,11.305209,23.380384,25.552917,11.292115,23.362726,25.55512,11.280545,23.327475,25.565844,11.266936,23.305206,25.586967,11.251483,23.31579,25.614349,11.235746,23.352438,25.64748,11.214075,23.401062,25.69471,11.177201,23.487968,25.711798,11.199377,23.571569,25.649658,11.312396,23.602541,25.589733,11.408429,23.600561,25.570297,11.46718,23.659069,25.563253,11.537304,23.721621,25.585634,11.584576,23.828579,200118G,canicula,mediterranean,40,female,mature,lower,tooth09,4

that is different from the reference file:
example/200118G_canicula_mediterranean_40_female_mature_lower_tooth04_4.pts,23.760645,14.822544,26.607994,23.460169,14.72399,26.149445,23.619444,14.667845,26.251095,23.519606,14.463796,25.761469,23.799814,14.451308,26.218939,23.817883,14.327648,26.021515,24.05011,14.500256,26.583118,23.731268,14.851231,26.612024,23.693602,14.879261,26.590559,23.657339,14.899388,26.562233,23.620415,14.917179,26.531328,23.591503,14.916238,26.493502,23.580864,14.887245,26.456419,23.555262,14.877494,26.415607,23.52702,14.865196,26.368336,23.579859,14.780132,26.356867,23.546961,14.772367,26.300602,23.504704,14.757745,26.230452,23.531639,14.690864,26.178947,23.574799,14.58428,26.049805,23.669212,14.445662,26.010353,23.800825,14.386982,26.109592,23.858444,14.317473,26.077599,23.894411,14.332585,26.170313,23.92621,14.366543,26.286236,23.955145,14.364937,26.324955,23.982096,14.327062,26.290644,24.00683,14.300524,26.272785,24.027893,14.302449,26.299009,24.04743,14.317135,26.343693,24.0672,14.343269,26.407444,24.082382,14.387399,26.492682,24.071802,14.447412,26.555712,23.957222,14.536147,26.573864,23.874788,14.572289,26.542034,23.817228,14.613439,26.521942,23.779778,14.664021,26.510342,23.76063,14.742847,26.568264,200118G,canicula,mediterranean,40,female,mature,lower,tooth04,4

Testing call from the command line...
File successfully generated: /home/patrik/scyland3d-review/Scyland3D/Scyland3D/landmarks.csv
File successfully generated: /home/patrik/scyland3d-review/Scyland3D/Scyland3D/landmarks_reordered.csv
File successfully generated: /home/patrik/scyland3d-review/Scyland3D/Scyland3D/landmarks_reversed.csv
Testing default behavior...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/patrik/scyland3d-review/Scyland3D/Scyland3D/Scyland3D.py", line 351, in _validation_against_ref
    dirn + "landmarks.csv", dirn + "test/landmarks_ref.csv"
  File "/home/patrik/scyland3d-review/Scyland3D/Scyland3D/Scyland3D.py", line 334, in _same_file
    assert line_ref == line_test, "Invalid line generated:\n" + line_test + "\nthat is different from the reference file:\n" + line_ref
AssertionError: Invalid line generated:
example/200118G_canicula_mediterranean_40_female_mature_lower_tooth09_4.pts,25.628664,11.627904,23.958033,25.294479,11.766243,23.443439,25.416937,11.636269,23.504972,25.285938,11.601955,23.1847,25.480515,11.458488,23.40572,25.424305,11.401969,23.213655,25.720415,11.227379,23.608505,25.605238,11.68239,23.968342,25.581594,11.735225,23.951746,25.55871,11.775233,23.927303,25.535694,11.803462,23.898464,25.509012,11.828192,23.866955,25.481352,11.8446,23.82785,25.486269,11.775678,23.780958,25.443384,11.805834,23.732676,25.394228,11.839259,23.66806,25.410519,11.719546,23.634127,25.351175,11.754179,23.546564,25.337692,11.711373,23.459862,25.341736,11.625697,23.339272,25.361479,11.536088,23.272907,25.453016,11.429392,23.314713,25.506357,11.353887,23.309586,25.548668,11.321219,23.384398,25.550634,11.305209,23.380384,25.552917,11.292115,23.362726,25.55512,11.280545,23.327475,25.565844,11.266936,23.305206,25.586967,11.251483,23.31579,25.614349,11.235746,23.352438,25.64748,11.214075,23.401062,25.69471,11.177201,23.487968,25.711798,11.199377,23.571569,25.649658,11.312396,23.602541,25.589733,11.408429,23.600561,25.570297,11.46718,23.659069,25.563253,11.537304,23.721621,25.585634,11.584576,23.828579,200118G,canicula,mediterranean,40,female,mature,lower,tooth09,4

that is different from the reference file:
example/200118G_canicula_mediterranean_40_female_mature_lower_tooth04_4.pts,23.760645,14.822544,26.607994,23.460169,14.72399,26.149445,23.619444,14.667845,26.251095,23.519606,14.463796,25.761469,23.799814,14.451308,26.218939,23.817883,14.327648,26.021515,24.05011,14.500256,26.583118,23.731268,14.851231,26.612024,23.693602,14.879261,26.590559,23.657339,14.899388,26.562233,23.620415,14.917179,26.531328,23.591503,14.916238,26.493502,23.580864,14.887245,26.456419,23.555262,14.877494,26.415607,23.52702,14.865196,26.368336,23.579859,14.780132,26.356867,23.546961,14.772367,26.300602,23.504704,14.757745,26.230452,23.531639,14.690864,26.178947,23.574799,14.58428,26.049805,23.669212,14.445662,26.010353,23.800825,14.386982,26.109592,23.858444,14.317473,26.077599,23.894411,14.332585,26.170313,23.92621,14.366543,26.286236,23.955145,14.364937,26.324955,23.982096,14.327062,26.290644,24.00683,14.300524,26.272785,24.027893,14.302449,26.299009,24.04743,14.317135,26.343693,24.0672,14.343269,26.407444,24.082382,14.387399,26.492682,24.071802,14.447412,26.555712,23.957222,14.536147,26.573864,23.874788,14.572289,26.542034,23.817228,14.613439,26.521942,23.779778,14.664021,26.510342,23.76063,14.742847,26.568264,200118G,canicula,mediterranean,40,female,mature,lower,tooth04,4

(scyland3d) patrik:~/scyland3d-review/Scyland3D/Scyland3D$ 
```

**Comment by ybayle** [comment]
> The Must supply order and order_factor. error seems gone.

:+1: 

> There's a different error now:

I haven't tested on Windows. I will check it and keep you up to date.

**Comment by ybayle** [comment]
I fixed the issue on Windows here, could you confirm everything is working fine on your side?

**Comment by patrikhuber** [comment]
More tests seem to pass now but I still got an error:
(this is in a  WSL shell so it might again have to do with line endings - or not, as two floating point values seem to be quite different)

```
$ python
Python 3.6.8 (default, Oct  7 2019, 12:59:55)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Scyland3D import Scyland3D
>>> Scyland3D.test_no_regression()
File successfully generated: /home/patrik/.virtualenvs/scyland3d/lib/python3.6/site-packages/Scyland3D/landmarks.csv
File successfully generated: /home/patrik/.virtualenvs/scyland3d/lib/python3.6/site-packages/Scyland3D/landmarks_reordered.csv
File successfully generated: /home/patrik/.virtualenvs/scyland3d/lib/python3.6/site-packages/Scyland3D/landmarks_reversed.csv
Testing default behavior...
Ok!
Testing reordering...
Ok!
Testing reversing...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patrik/.virtualenvs/scyland3d/lib/python3.6/site-packages/Scyland3D/Scyland3D.py", line 473, in test_no_regression
    _validation_against_ref()
  File "/home/patrik/.virtualenvs/scyland3d/lib/python3.6/site-packages/Scyland3D/Scyland3D.py", line 375, in _validation_against_ref
    dirn + "landmarks_reversed.csv", dirn + "test/landmarks_reversed_ref.csv"
  File "/home/patrik/.virtualenvs/scyland3d/lib/python3.6/site-packages/Scyland3D/Scyland3D.py", line 348, in _same_file
    assert line_ref == line_test, "Invalid line generated:\n" + line_test + "\nthat is different from the reference file:\n" + line_ref
AssertionError: Invalid line generated:
example/200118H_canicula_mediterranean_47_female_mature_upper_tooth04_3.pts,15.250192222098738,21.508294685741003,28.678250805861243,15.538475872969613,21.315691297389527,28.44522452981047,15.412222002840693,21.26600127842893,28.544590769400006,15.716011901860037,20.940988874361956,28.232551859944113,15.321003219633203,20.929705218359096,28.671938345414056,15.385567752898783,20.773448718255768,28.62005217882164,15.044217842301663,20.862119786950778,29.01015235346634,15.280107387672018,21.526176742024028,28.66775158604194,15.32016829776629,21.531716073352488,28.640497426508908,15.356263793839194,21.51848580106889,28.612198967265464,15.38706693132819,21.506442769862563,28.589136153946235,15.41582177874779,21.49417770434044,28.56699502742536,15.43422670225145,21.471456221987697,28.553802789271113,15.44618470828529,21.44582790694996,28.546635853173925,15.461553248298133,21.423917007187256,28.534659814494024,15.478662622688843,21.40206336691809,28.519027844466407,15.501531922335836,21.379159154157453,28.493967367426425,15.531206075844668,21.349305640929018,28.455807673160695,15.485155720083032,21.29784494290733,28.48724824579142,15.556924362192811,21.117649540829568,28.42137611223139,15.50403626716043,20.94949452454902,28.48056039616332,15.3549235878322,20.853872688018733,28.644836365976715,15.354441539203991,20.7712248168309,28.660442274705144,15.318230969761704,20.7869293325365,28.708930605756212,15.285078474811566,20.803707476108308,28.754579286546186,15.254424366245278,20.82061625522485,28.79583384298295,15.232625333366101,20.809478775537595,28.81873616054578,15.216799746854711,20.764003550805196,28.827747724899883,15.189599739565143,20.764114082361466,28.857830582796407,15.159992006074468,20.781359000017076,28.891251832901638,15.130997634685242,20.793259298842436,28.924030919872003,15.100843105169742,20.80799305027017,28.9609132676764,15.07096531815483,20.833419079058142,28.99349293847223,15.112607287397035,20.949018519924085,28.965924240278213,15.186083400519212,21.033059514371658,28.863261074630934,15.242057300694782,21.11957457419216,28.78464398025325,15.27852206033822,21.216743637876064,28.72257883244919,15.27852649703689,21.35115009152016,28.688980969881268,200118H,canicula,mediterranean,47,female,mature,upper,tooth04,3

that is different from the reference file:
example/200118H_canicula_mediterranean_47_female_mature_upper_tooth04_3.pts,15.250192222093075,21.508294685740747,28.678250805856255,15.538475872963792,21.315691297389172,28.44522452980537,15.412222002834772,21.26600127842862,28.5445907693948,15.716011901853829,20.940988874361615,28.23255185993866,15.321003219626819,20.92970521835876,28.671938345408446,15.385567752892229,20.773448718255406,28.620052178815882,15.04421784229508,20.86211978695041,29.01015235346056,15.28010738766638,21.526176742023747,28.66775158603698,15.32016829776067,21.53171607335219,28.64049742650397,15.356263793833568,21.518485801068575,28.61219896726052,15.387066931322554,21.506442769862232,28.589136153941293,15.415821778742147,21.494177704340103,28.566995027420415,15.434226702245786,21.47145622198735,28.553802789266147,15.446184708279594,21.445827906949607,28.546635853168933,15.461553248292415,21.423917007186894,28.534659814489018,15.478662622683105,21.402063366917726,28.519027844461384,15.501531922330077,21.379159154157087,28.49396736742138,15.531206075838886,21.34930564092866,28.455807673155633,15.48515572007717,21.297844942906995,28.487248245786276,15.556924362186754,21.117649540829213,28.421376112226074,15.504036267154138,20.94949452454867,28.480560396157795,15.354923587825736,20.853872688018384,28.644836365971038,15.354441539197417,20.771224816830536,28.660442274699374,15.318230969755131,20.786929332536122,28.708930605750446,15.285078474804996,20.803707476107924,28.754579286540423,15.254424366238714,20.820616255224458,28.795833842977196,15.232625333359518,20.809478775537205,28.818736160540006,15.216799746848071,20.764003550804816,28.827747724894056,15.189599739558494,20.764114082361086,28.857830582790573,15.15999200606783,20.781359000016696,28.89125183289581,15.1309976346786,20.793259298842056,28.924030919866173,15.10084310516311,20.807993050269786,28.96091326767058,15.070965318148213,20.83341907905776,28.993492938466424,15.112607287390576,20.94901851992368,28.965924240272553,15.186083400512892,21.033059514371274,28.863261074625395,15.242057300688595,21.119574574191795,28.78464398024782,15.278522060332175,21.216743637875723,28.722578832443883,15.278526497031024,21.35115009151986,28.688980969876113,200118H,canicula,mediterranean,47,female,mature,upper,tooth04,3

>>>
```

**Comment by ybayle** [comment]
All values seem to be different at 10^-11 this might be platform specific and due to rounding errors. Depending on the python version and OS, the minimum epsilon that can be represented is greater than 1e-15 obtained with:
```
import numpy as np
print(np.finfo(np.float))
```

**Comment by patrikhuber** [comment]
Would it make sense to check for an eps of 10^-9 or 10^-10 or so in the tests? As far as I understand, reversing involves some mathematical operations (right?), so a difference this small is expected?

**Comment by ybayle** [comment]
This kind of difference is indeed expected. I'll fix this.

**Comment by ybayle** [comment]
Could you check after a `git pull` that the last commits solve your issue? Thanks!
If so, I'll update the software version on pip and resubmit it to the JOSS editor.

**Comment by patrikhuber** [comment]
I can confirm that all tests pass now!
