### ISSUE TITLE
`AssertionError: Must supply order and order_factor` when supplying -f and -o

### ISSUE THREAD

**Issue by patrikhuber** [ybayle/Scyland3D#12]
I was trying to play around with the command-line, using the following line from the readme (slightly modified - I added `-i ...`):

`python -m Scyland3D.Scyland3D -i scyland3d-review/Scyland3D/Scyland3D/example/ -f "upper" -o "36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 37"`

And I get `AssertionError: Must supply order and order_factor.`. But I did supply both (which should be the -f and -o), so I am a bit confused.

Full output:

```
$ python -m Scyland3D.Scyland3D -i scyland3d-review/Scyland3D/Scyland3D/example/ -f "upper" -o "36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 37"
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/patrik/.virtualenvs/scyland3d/lib/python3.6/site-packages/Scyland3D/Scyland3D.py", line 492, in <module>
    pts2csv(args.indir, args.outdir, args.mirror_factor, args.order, args.order_factor, args.feature_names, args.verbose)
  File "/home/patrik/.virtualenvs/scyland3d/lib/python3.6/site-packages/Scyland3D/Scyland3D.py", line 231, in pts2csv
    ), "Must supply order and order_factor."
AssertionError: Must supply order and order_factor.
```

**Comment by ybayle** [comment]
My bad, it was a typo in the ReadMe: the order must be supplied by the option `-r` as depicted in the help message: 
```
Scyland3D: Processing 3D landmarks.

optional arguments:
  -h, --help            show this help message and exit
  -i INDIR, --indir INDIR
                        the input directory containing the landmarks to
                        process
  -o OUTDIR, --outdir OUTDIR
                        the output directory containing the landmarks to
                        process
  -m MIRROR_FACTOR, --mirror_factor MIRROR_FACTOR
                        the factor to be used when mirroring the corresponding
                        landmarks
  -r ORDER, --order ORDER
                        the new order to apply to the landmarks
  -f ORDER_FACTOR, --order_factor ORDER_FACTOR
                        the factor to be used when reordering the
                        corresponding landmarks
  -n FEATURE_NAMES, --feature_names FEATURE_NAMES
                        the feature names to use in the header in the output
                        file
  -v, --verbose         whether to output the processing steps
```
The `-o` specifies the output file. The ReadMe has been fixed.

**Comment by patrikhuber** [comment]
Ah yes, this fixes it, thanks!
